# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A loop in c++ to speed up
#'
#' @param R a matrix (not sparse matrix, use \code{as.matrix(R)} to convert if necessary)
#' @param V a symmetric matrix (not sparse matrix)
#' @param iV the inverse of V (not sparse matrix)
#' @param X model matrix (not sparse matrix)
#' @export
loop_cpp <- function(R, V, iV, X) {
    .Call('rr2_loop_cpp', PACKAGE = 'rr2', R, V, iV, X)
}

